### ISSUE TITLE
Debian/Ubuntu Repository

### ISSUE THREAD

**Issue by trymeouteh** [BusKill/buskill-app#45] opened 2022-11-25 19:19 UTC
**Is your feature request related to a problem? Please describe.**
A self hosted Debian/Ubuntu repository for the Buskill app

**Describe the solution you'd like**
The ability to install Buskill on Debian and Ubuntu using a 3rd party repository and receive updates to Buskill right when the updates are released.

**Describe alternatives you've considered**
Flatpak
AppImage
Pacstall

**Additional context**
None

**Comment by maltfield** [comment] 2022-11-25 19:21
@trymeouteh any reason we should shoot for a self-hosted repo instead of the official Debian repos as described in #31?

 * https://github.com/BusKill/buskill-app/issues/31

**Comment by maltfield** [comment] 2022-11-25 19:23
> Describe alternatives you've considered
> Flatpak
> AppImage
> Pacstall

btw, the release is already a signed AppImage, and it has a built-in update function that securely updates itself with the latest version.

I wouldn't use FlatPak as I've yet to find any documentation on if/how it actually secures the supply chain.

**Comment by trymeouteh** [comment] 2022-11-25 19:28
I cannot find a download page on the website and I do not see any AppImages in the github releases

**Comment by maltfield** [comment] 2022-11-25 19:35
> I cannot find a download page on the website and I do not see any AppImages in the github releases
> 
> An AppImage would be best to allow support on all distros as a easy to use portable package. An Debian/Ubuntu repository would be ideal to have a lighter package than an AppImage.

See our documentation for how to download/install/verify the BusKill app:

 * https://docs.buskill.in/buskill-app/en/v0.6.0/software_usr/download.html

Is there anything unclear about this in the documentation that we can improve? Is there anything we can change to make this easier for you to find?

**Comment by trymeouteh** [comment] 2022-11-25 19:42
Ah, the AppImage is inside the tarball file. Was not expecting that.

**Comment by maltfield** [comment] 2022-11-25 19:49
I don't use Arch, but if there's anything I can do to assist with that, please let me know :)

**Comment by maltfield** [comment] 2022-11-25 20:27
Closing as duplicate of #31. Please re-open if further action is required.

**Closed by maltfield** 2022-11-25 20:27 UTC
Labels: documentation, duplicate
