### ISSUE TITLE
Move the Debian-specific GPG signature from the Linux tarball to the source tarball

### ISSUE THREAD

**Issue by fmarier** [BusKill/buskill-app#53] opened 2022-12-21 21:02 UTC
The Debian packaging is based on the source tarball and so that's the tarball that would benefit from a separate detached GPG signature.

At the moment the Debian-specific signature is on the Linux (AppImage) tarball.

**Comment by maltfield** [comment] 2022-12-21 22:02
TODO:
1. Manually sign the v0.6.0 tag's source tarball in a detached signature and upload it to the release
2. Manually delete the v0.6.0 .AppImage tarball's detached signature
3. Update the `Release Workflow` documentation to check & sign the source tarball, not the .AppImage tarball

**Comment by maltfield** [comment] 2022-12-21 22:58
For manually signing the v0.6.0 tag's release source tarball, first I download the file to be signed

```
user@buskill:~/Downloads$ wget https://github.com/BusKill/buskill-app/archive/refs/tags/v0.6.0.tar.gz
--2022-12-21 16:44:38--  https://github.com/BusKill/buskill-app/archive/refs/tags/v0.6.0.tar.gz
Resolving github.com (github.com)... 140.82.113.3
Connecting to github.com (github.com)|140.82.113.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/BusKill/buskill-app/tar.gz/refs/tags/v0.6.0 [following]
--2022-12-21 16:44:38--  https://codeload.github.com/BusKill/buskill-app/tar.gz/refs/tags/v0.6.0
Resolving codeload.github.com (codeload.github.com)... 140.82.114.10
Connecting to codeload.github.com (codeload.github.com)|140.82.114.10|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘v0.6.0.tar.gz’

v0.6.0.tar.gz             [         <=>              ] 176.58M   371KB/s    in 4m 28s  

2022-12-21 16:49:07 (675 KB/s) - ‘v0.6.0.tar.gz’ saved [185152944]

user@buskill:~/Downloads$ sha256sum v0.6.0.tar.gz
a727ae008fd889fc732f21c4bdd61faedc496c896d841b9697083bd0c6be7481  v0.6.0.tar.gz
user@buskill:~/Downloads$ du -sh v0.6.0.tar.gz 
177M	v0.6.0.tar.gz
user@buskill:~/Downloads$ 
```

**Comment by maltfield** [comment] 2022-12-21 23:02
I extract the tarball and diff it against my local repo to check its authenticity and integrity

```
user@buskill:~/Downloads$ tar -xzf v0.6.0.tar.gz
user@buskill:~/Downloads$ ls
buskill-app-0.6.0  v0.6.0.tar.gz
user@buskill:~/Downloads$ 
user@buskill:~/Downloads$ ls buskill-app-0.6.0
build  CHANGELOG  docs  KEYS  LICENSE  README.md  src  updates
user@buskill:~/Downloads$ 
user@buskill:~/Downloads$ cd ../sandbox/buskill-app
user@buskill:~/sandbox/buskill-app$ git checkout v0.6.0
warning: refname 'v0.6.0' is ambiguous.
Switched to branch 'v0.6.0'
user@buskill:~/sandbox/buskill-app$ 
```

Unfortunately, I did find some differences. Some of which are just untracked runtime files ignored by git

```
user@buskill:~/sandbox/buskill-app$ diff -rq . ~/Downloads/buskill-app-0.6.0/
Only in .: .buskill
Only in .: dist
Only in ./docs: _build
Only in ./docs: buskill.1
Only in ./docs/_extensions: __pycache__
Only in ./docs/_extensions/sphinxemoji: __pycache__
Files ./docs/software_usr/cli.rst and /home/user/Downloads/buskill-app-0.6.0/docs/software_usr/cli.rst differ
Only in .: .git
Only in .: gnupg
Only in ./src/packages/buskill: __pycache__
Only in ./src/packages/garden/navigationdrawer: __pycache__
Only in ./src/packages/garden/progressspinner: __pycache__
Only in ./src: __pycache__
Files ./updates/v1/meta.json and /home/user/Downloads/buskill-app-0.6.0/updates/v1/meta.json differ
Files ./updates/v1/meta.json.asc and /home/user/Downloads/buskill-app-0.6.0/updates/v1/meta.json.asc differ
user@buskill:~/sandbox/buskill-app$ git status
On branch v0.6.0
Revert currently in progress.
  (run "git revert --continue" to continue)
  (use "git revert --skip" to skip this patch)
  (use "git revert --abort" to cancel the revert operation)

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.buskill/
	docs/buskill.1

nothing added to commit but untracked files present (use "git add" to track)
user@buskill:~/sandbox/buskill-app$ 
```

Deleting the files and the list is a bit shorter

```
user@buskill:~/sandbox/buskill-app$ diff -rq . ~/Downloads/buskill-app-0.6.0/
Only in .: dist
Only in ./docs: _build
Only in ./docs/_extensions: __pycache__
Only in ./docs/_extensions/sphinxemoji: __pycache__
Files ./docs/software_usr/cli.rst and /home/user/Downloads/buskill-app-0.6.0/docs/software_usr/cli.rst differ
Only in .: .git
Only in .: gnupg
Only in ./src/packages/buskill: __pycache__
Only in ./src/packages/garden/navigationdrawer: __pycache__
Only in ./src/packages/garden/progressspinner: __pycache__
Only in ./src: __pycache__
Files ./updates/v1/meta.json and /home/user/Downloads/buskill-app-0.6.0/updates/v1/meta.json differ
Files ./updates/v1/meta.json.asc and /home/user/Downloads/buskill-app-0.6.0/updates/v1/meta.json.asc differ
user@buskill:~/sandbox/buskill-app$ 
```

**Comment by maltfield** [comment] 2022-12-21 23:05
Looks like part of the problem was the ambiguity of `v0.6.0`, which is the name of both a branch and a tag. The Github release is actually a tag, not a branch. If we're specific in checking-out the tag, then the list is shorter

```
user@buskill:~/sandbox/buskill-app$ git checkout refs/tags/v0.6.0
Note: switching to 'refs/tags/v0.6.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at e2242e2 updated changelog for new release
user@buskill:~/sandbox/buskill-app$ 

user@buskill:~/sandbox/buskill-app$ diff -rq . ~/Downloads/buskill-app-0.6.0/
Only in .: dist
Only in ./docs: _build
Only in ./docs/_extensions: __pycache__
Only in ./docs/_extensions/sphinxemoji: __pycache__
Only in .: .git
Only in .: gnupg
Only in ./src/packages/buskill: __pycache__
Only in ./src/packages/garden/navigationdrawer: __pycache__
Only in ./src/packages/garden/progressspinner: __pycache__
Only in ./src: __pycache__
user@buskill:~/sandbox/buskill-app$ 
```

**Comment by maltfield** [comment] 2022-12-21 23:16
If I check `.gitignore`, then it makes sense why some of these files are in my local sandbox yet not reported as `untracked` with `git status`  and not included in the source tarball

```
user@buskill:~/sandbox/buskill-app$ diff -rq . ~/Downloads/buskill-app-0.6.0/
Only in .: dist
Only in ./docs: _build
Only in ./docs/_extensions: __pycache__
Only in ./docs/_extensions/sphinxemoji: __pycache__
Only in .: .git
Only in .: gnupg
Only in ./src/packages/buskill: __pycache__
Only in ./src/packages/garden/navigationdrawer: __pycache__
Only in ./src/packages/garden/progressspinner: __pycache__
Only in ./src: __pycache__
user@buskill:~/sandbox/buskill-app$ 

user@buskill:~/sandbox/buskill-app$ cat .gitignore
__pycache__
*.pyc
*.swp
/dist
.DS_Store
user@buskill:~/sandbox/buskill-app$ 
```

Removing the ones that match against the `.gitignore` file, we have these left:

```

```

**Comment by maltfield** [comment] 2022-12-21 23:31
I signed the now-verified tarball and uploaded its detached signature to the release (filename = ` v0.6.0.tar.gz.asc `). It can be downloaded here:

 * https://github.com/BusKill/buskill-app/releases/tag/v0.6.0
 * https://github.com/BusKill/buskill-app/releases/download/v0.6.0/v0.6.0.tar.gz.asc

**Comment by maltfield** [comment] 2022-12-21 23:33
> 2. Manually delete the v0.6.0 .AppImage tarball's detached signature

I also deleted the file ` buskill-lin-v0.6.0-x86_64.tbz.asc` from the release.

**Comment by maltfield** [comment] 2022-12-21 23:34
@fmarier does this file meet your needs for #31 ?

 * https://github.com/BusKill/buskill-app/releases/tag/v0.6.0
 * https://github.com/BusKill/buskill-app/releases/download/v0.6.0/v0.6.0.tar.gz.asc

**Comment by fmarier** [comment] 2022-12-22 16:04
That looks good:
```
$ LANG=C gpg --verify buskill-app-0.6.0.tar.gz.asc
gpg: assuming signed data in 'buskill-app-0.6.0.tar.gz'
gpg: Signature made Wed Dec 21 18:29:35 2022 EST
gpg:                using RSA key 798DC1101F3DEC428ADE124D68B8BCB0C5023905
gpg: Good signature from "BusKill Releases Signing Key 2020.07 <releases@buskill.in>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: E0AF FF57 DC00 FBE0 5635  8761 4AE2 1E19 36CE 786A
     Subkey fingerprint: 798D C110 1F3D EC42 8ADE  124D 68B8 BCB0 C502 3905
```
All I had to do was to rename the file manually from `v0.6.0.tar.gz.asc` to `buskill-app-0.6.0.tar.gz.asc` because the source code tarball ends up with a default name of `buskill-app-0.6.0.tar.gz` instead of `v0.6.0.tar.gz` when I download it in a browser.

**Comment by maltfield** [comment] 2022-12-27 16:53
I'm looking into making changes to `.gitattributes` so that I can try to get GitHub to minimize the contents of the source code tarball that it creates with our release, such that it excludes all binary blobs, if possible

 * https://github.com/BusKill/buskill-app/issues/31#issuecomment-1365570844

**Comment by maltfield** [comment] 2022-12-27 16:55
So we can exclude some files from being created by `git archive` by adding the file and the `gitattributes` attribute = `export-ignore`

 * https://github.com/fmarier/tmd710_tncsetup/blob/c668aef13350fa7ab24603049ecaba5749336e85/.gitattributes#L1-L5

For more info, see:

 * https://feeding.cloud.geek.nz/posts/excluding-files-from-git-archive/

**Comment by maltfield** [comment] 2022-12-27 17:00
From #31, we should remove these dirs from the archive:

```
build/
updates/
.github/
```

We should also probably go ahead and remove these files just for a cleaner archive

```
.gitignore
.gitattributes
```

It would also make sense to delete all of the `docs/` directory (which has some large images), but doing a delete-everything-in-this-dir-except-files-in-this-allowlist seems less trivial, so I'll skip that for now

**Comment by maltfield** [comment] 2022-12-27 17:16
I don't want to create a new release, so I'm going to test this on the release before the latest release = `v0.5.0`

Before making any changes, I confirmed that `v0.5.0` is currently pointed to commit = ```

 * https://github.com/BusKill/buskill-app/releases/tag/v0.5.0

```

```

**Comment by maltfield** [comment] 2022-12-27 17:27
I added the `.gitattributes` file to the `v0.5.0` branch, committed it, and pushed it to GitHub.

Then I deleted the old `v0.5.0` tag, replaced it to point to the new commit, and pushed that to GitHub.

```
user@buskill:~/sandbox/buskill-app$ git commit -a
[v0.5.0 b2dd3fc] attempting to add `.gitattributes` to remove binary blobs from our sourcecode built by GitHub for releases with `git archive`
 1 file changed, 5 insertions(+)
 create mode 100644 .gitattributes
user@buskill:~/sandbox/buskill-app$ 

user@buskill:~/sandbox/buskill-app$ git push
Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Delta compression using up to 2 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 1.15 KiB | 196.00 KiB/s, done.
Total 3 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To github.com:BusKill/buskill-app.git
   bffeeaa..b2dd3fc  v0.5.0 -> v0.5.0
user@buskill:~/sandbox/buskill-app$

user@buskill:~/sandbox/buskill-app$ git tag v0.5.0
fatal: tag 'v0.5.0' already exists
user@buskill:~/sandbox/buskill-app$ git tag -d v0.5.0
Deleted tag 'v0.5.0' (was 996c0f6)
user@buskill:~/sandbox/buskill-app$ git tag v0.5.0
user@buskill:~/sandbox/buskill-app$ 

user@buskill:~/sandbox/buskill-app$ git push origin refs/tags/v0.5.0
To github.com:BusKill/buskill-app.git
 ! [rejected]        v0.5.0 -> v0.5.0 (already exists)
error: failed to push some refs to 'github.com:BusKill/buskill-app.git'
hint: Updates were rejected because the tag already exists in the remote.
user@buskill:~/sandbox/buskill-app$ 

user@buskill:~/sandbox/buskill-app$ git push -f origin refs/tags/v0.5.0
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
To github.com:BusKill/buskill-app.git
 + 996c0f6...b2dd3fc v0.5.0 -> v0.5.0 (forced update)
user@buskill:~/sandbox/buskill-app$ 
```

**Comment by maltfield** [comment] 2022-12-27 17:36
The `v0.5.0` release page now says that it points to commit `996c0f6` at the top of the page

 * https://github.com/BusKill/buskill-app/releases/tag/v0.5.0

It took a few minutes, but eventually the timestamp column of the `Source code` files on the release page changed from `July 22` to `X minutes ago`. I downloaded it, and confirmed it has been updated

```
user@disp7201:~/Downloads$ wget https://github.com/BusKill/buskill-app/archive/refs/tags/v0.5.0.tar.gz
--2022-12-27 11:34:33--  https://github.com/BusKill/buskill-app/archive/refs/tags/v0.5.0.tar.gz
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/BusKill/buskill-app/tar.gz/refs/tags/v0.5.0 [following]
--2022-12-27 11:34:33--  https://codeload.github.com/BusKill/buskill-app/tar.gz/refs/tags/v0.5.0
Resolving codeload.github.com (codeload.github.com)... 140.82.121.9
Connecting to codeload.github.com (codeload.github.com)|140.82.121.9|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘v0.5.0.tar.gz’

v0.5.0.tar.gz           [               <=>  ]  21.70M  6.35MB/s    in 3.9s    

2022-12-27 11:34:38 (5.53 MB/s) - ‘v0.5.0.tar.gz’ saved [22759212]

user@disp7201:~/Downloads$ 
user@disp7201:~/Downloads$ du -sh v0.5.0.tar.gz 
22M	v0.5.0.tar.gz
user@disp7201:~/Downloads$ 

user@disp7201:~/Downloads$ tar -xzf v0.5.0.tar.gz
user@disp7201:~/Downloads$ cd buskill-app-0.5.0/
user@disp7201:~/Downloads$ 

user@disp7201:~/Downloads/buskill-app-0.5.0$ ls -lah
total 148K
drwxr-xr-x  4 user user 4.0K Dec 27 11:18 .
drwxr-xr-x  4 user user 4.0K Dec 27 11:35 ..
-rw-r--r--  1 user user  810 Dec 27 11:18 CHANGELOG
drwxr-xr-x 13 user user 4.0K Dec 27 11:18 docs
-rw-r--r--  1 user user  86K Dec 27 11:18 KEYS
-rw-r--r--  1 user user  35K Dec 27 11:18 LICENSE
-rw-r--r--  1 user user 3.6K Dec 27 11:18 README.md
drwxr-xr-x  5 user user 4.0K Dec 27 11:18 src
user@disp7201:~/Downloads/buskill-app-0.5.0$ 

user@disp7201:~/Downloads/buskill-app-0.5.0$ du -sh *
4.0K	CHANGELOG
22M	docs
88K	KEYS
36K	LICENSE
4.0K	README.md
2.8M	src
user@disp7201:~/Downloads$ 
```

**Comment by maltfield** [comment] 2022-12-27 17:56
Since I've confirmed that process works, I did the same for the `v0.6.0` release.

```
user@buskill:~/sandbox/buskill-app$ git checkout v0.6.0
warning: refname 'v0.6.0' is ambiguous.
Switched to branch 'v0.6.0'
user@buskill:~/sandbox/buskill-app$

user@buskill:~/sandbox/buskill-app$ cat > .gitattributes <<'EOF'
.gitattributes export-ignore
.github export-ignore
.gitignore export-ignore
build/ export-ignore
updates/ export-ignore
EOF
user@buskill:~/sandbox/buskill-app$ git add .gitattributes
user@buskill:~/sandbox/buskill-app$ 
user@buskill:~/sandbox/buskill-app$ git commit -am 'adding `.gitattributes` to remove binary blobs from our sourcecode built by GitHub for releases with `git archive`'
[v0.6.0 52d699a] adding `.gitattributes` to remove binary blobs from our sourcecode built by GitHub for releases with `git archive`
 1 file changed, 5 insertions(+)
 create mode 100644 .gitattributes
user@buskill:~/sandbox/buskill-app$ 
user@buskill:~/sandbox/buskill-app$ git push
Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Delta compression using up to 2 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 1.09 KiB | 185.00 KiB/s, done.
Total 3 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To github.com:BusKill/buskill-app.git
   b712e4c..52d699a  v0.6.0 -> v0.6.0
user@buskill:~/sandbox/buskill-app$ 
user@buskill:~/sandbox/buskill-app$ git tag -d v0.6.0
Deleted tag 'v0.6.0' (was e2242e2)
user@buskill:~/sandbox/buskill-app$ git tag v0.6.0
user@buskill:~/sandbox/buskill-app$ git push -f origin refs/tags/v0.6.0
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
To github.com:BusKill/buskill-app.git
 + e2242e2...52d699a v0.6.0 -> v0.6.0 (forced update)
user@buskill:~/sandbox/buskill-app$ 
```

And in the `dev` branch too.

```
user@buskill:~/sandbox/buskill-app$ git checkout dev
Switched to branch 'dev'
Your branch is up to date with 'origin/dev'.
user@buskill:~/sandbox/buskill-app$ 
user@buskill:~/sandbox/buskill-app$ cat > .gitattributes <<'EOF'
.gitattributes export-ignore
.github export-ignore
.gitignore export-ignore
build/ export-ignore
updates/ export-ignore
EOF
user@buskill:~/sandbox/buskill-app$ 
user@buskill:~/sandbox/buskill-app$ git add .gitattributes
user@buskill:~/sandbox/buskill-app$ 
user@buskill:~/sandbox/buskill-app$ git commit -am 'adding `.gitattributes` to remove binary blobs from our sourcecode built by GitHub for releases with `git archive`'
[dev e1539d2] adding `.gitattributes` to remove binary blobs from our sourcecode built by GitHub for releases with `git archive`
 1 file changed, 5 insertions(+)
 create mode 100644 .gitattributes
user@buskill:~/sandbox/buskill-app$ 
user@buskill:~/sandbox/buskill-app$ git push
Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Delta compression using up to 2 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 1.09 KiB | 222.00 KiB/s, done.
Total 3 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To github.com:BusKill/buskill-app.git
   7d7f44c..e1539d2  dev -> dev
user@buskill:~/sandbox/buskill-app$ 
```

**Comment by maltfield** [comment] 2022-12-27 18:07
Now that I've updated the source tarball for release v0.6.0, I need to update the signature created [above](https://github.com/BusKill/buskill-app/issues/53#issuecomment-1362218836).

Again, I start by verifying a diff of the source tarball's contents against my local sandbox

```
user@buskill:~/Downloads$ wget wget https://github.com/BusKill/buskill-app/archive/refs/tags/v0.6.0.tar.gz
--2022-12-27 11:58:16--  http://wget/
Resolving wget (wget)... failed: Name or service not known.
wget: unable to resolve host address ‘wget’
--2022-12-27 11:58:16--  https://github.com/BusKill/buskill-app/archive/refs/tags/v0.6.0.tar.gz
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/BusKill/buskill-app/tar.gz/refs/tags/v0.6.0 [following]
--2022-12-27 11:58:17--  https://codeload.github.com/BusKill/buskill-app/tar.gz/refs/tags/v0.6.0
Resolving codeload.github.com (codeload.github.com)... 140.82.121.10
Connecting to codeload.github.com (codeload.github.com)|140.82.121.10|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘v0.6.0.tar.gz’

v0.6.0.tar.gz           [               <=>  ]  21.71M  6.56MB/s    in 3.3s    

2022-12-27 11:58:21 (6.56 MB/s) - ‘v0.6.0.tar.gz’ saved [22766983]

FINISHED --2022-12-27 11:58:21--
Total wall clock time: 5.1s
Downloaded: 1 files, 22M in 3.3s (6.56 MB/s)
user@buskill:~/Downloads$ 

user@buskill:~/Downloads$ sha256sum v0.6.0.tar.gz
013ee5b0d3c09f2afcb0dc80fe47191f597b8734e91b44da101c2faf4ff3dd71  v0.6.0.tar.gz
user@buskill:~/Downloads$ 

user@buskill:~/Downloads$ du -sh v0.6.0.tar.gz 
22M	v0.6.0.tar.gz
user@buskill:~/Downloads$ 

user@buskill:~/Downloads$ tar -xzf v0.6.0.tar.gz
user@buskill:~/Downloads$ ls
buskill-app-0.6.0  v0.6.0.tar.gz
user@buskill:~/Downloads$ 

user@buskill:~/Downloads$ ls buskill-app-0.6.0/
CHANGELOG  docs  KEYS  LICENSE  README.md  src
user@buskill:~/Downloads$ 

user@buskill:~/Downloads$ cd ../sandbox/buskill-app
user@buskill:~/sandbox/buskill-app$ 
user@buskill:~/sandbox/buskill-app$ git checkout refs/tags/v0.6.0
Note: switching to 'refs/tags/v0.6.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 52d699a adding `.gitattributes` to remove binary blobs from our sourcecode built by GitHub for releases with `git archive`
user@buskill:~/sandbox/buskill-app$ 

user@buskill:~/sandbox/buskill-app$ diff -rq . ~/Downloads/buskill-app-0.6.0/
Only in .: build
Only in .: dist
Only in ./docs: _build
Only in ./docs/_extensions: __pycache__
Only in ./docs/_extensions/sphinxemoji: __pycache__
Only in ./docs: .gitignore
Only in .: .git
Only in .: .gitattributes
Only in .: .github
Only in .: .gitignore
Only in .: gnupg
Only in ./src/packages/buskill: __pycache__
Only in ./src/packages/garden/navigationdrawer: __pycache__
Only in ./src/packages/garden/progressspinner: __pycache__
Only in ./src: __pycache__
Only in .: updates
user@buskill:~/sandbox/buskill-app$ 
```

As before, we're not concerned if there's files absent from the source tarball if they're present in `.gitignore`. And now we also aren't concerned about files absent if they're listed in `.gitattributes` with `export-ignore`

```
user@buskill:~/sandbox/buskill-app$ cat .gitignore
__pycache__
*.pyc
*.swp
/dist
.DS_Store
user@buskill:~/sandbox/buskill-app$ 

user@buskill:~/sandbox/buskill-app$ cat docs/.gitignore 
*.swp
/_build
/doctrees
/html
*.pyc
user@buskill:~/sandbox/buskill-app$ 

user@buskill:~/sandbox/buskill-app$ cat .gitattributes 
.gitattributes export-ignore
.github export-ignore
.gitignore export-ignore
build/ export-ignore
updates/ export-ignore
user@buskill:~/sandbox/buskill-app$ 
```

Removing those matches, we only have two relevant diffs left

```
Only in .: .git
Only in .: gnupg
```

But, again, `.git` missing from `git archive` is expected.

And `gnupg` is empty, so it doesn't matter. I also went ahead and removed this empty `gnupg` dir from the `dev` branch so it doesn't keep coming-up in diffs

```
user@buskill:~/sandbox/buskill-app$ ls -lah gnupg/
total 8.0K
drwx------  2 user user 4.0K Jun 26  2022 .
drwxr-xr-x 10 user user 4.0K Dec 27 12:00 ..
user@buskill:~/sandbox/buskill-app$ 

user@buskill:~/sandbox/buskill-app$ git checkout dev
Previous HEAD position was 52d699a adding `.gitattributes` to remove binary blobs from our sourcecode built by GitHub for releases with `git archive`
Switched to branch 'dev'
Your branch is up to date with 'origin/dev'.
user@buskill:~/sandbox/buskill-app$ 

user@buskill:~/sandbox/buskill-app$ ls -lah gnupg
total 8.0K
drwx------  2 user user 4.0K Jun 26  2022 .
drwxr-xr-x 10 user user 4.0K Dec 27 12:05 ..
user@buskill:~/sandbox/buskill-app$ 

user@buskill:~/sandbox/buskill-app$ rm -rf gnupg
user@buskill:~/sandbox/buskill-app$ 
```

**Comment by maltfield** [comment] 2022-12-27 18:14
> 1. Manually sign the v0.6.0 tag's source tarball in a detached signature and upload it to the v0.6.0 release

I went ahead and deleted the old signed "Source code" tarball and signed the now-verified tarball that excludes binary blobs.

As before, it can be downloaded here:

 * https://github.com/BusKill/buskill-app/releases/tag/v0.6.0 # in the browser
 * https://github.com/BusKill/buskill-app/releases/download/v0.6.0/v0.6.0.tar.gz.asc

**Comment by maltfield** [comment] 2022-12-27 18:15
@fmarier does this new source tarball & signature meet your needs for #31 ?

 * https://github.com/BusKill/buskill-app/releases/tag/v0.6.0
 * https://github.com/BusKill/buskill-app/releases/download/v0.6.0/v0.6.0.tar.gz.asc

**Comment by fmarier** [comment] 2022-12-27 18:15
> It would also make sense to delete all of the `docs/` directory (which has some large images), but doing a delete-everything-in-this-dir-except-files-in-this-allowlist seems less trivial, so I'll skip that for now

If you end up doing this, then I'd suggest generating the manpage (the `.1` file) and then including that in the tarball. At the moment, I do need the `docs/` directory because I generate the manpage based on the source `.rst` file: https://salsa.debian.org/debian/buskill/-/blob/da63f4b0477f33bff48832b7aebc54b25a4a17dd/debian/rules#L23

**Comment by fmarier** [comment] 2022-12-31 07:47
> @fmarier does this new source tarball & signature meet your needs for #31 ?
> 
> * https://github.com/BusKill/buskill-app/releases/tag/v0.6.0
> * https://github.com/BusKill/buskill-app/releases/download/v0.6.0/v0.6.0.tar.gz.asc

That looks great.

I will do an initial upload using the tarball from https://github.com/BusKill/buskill-app/releases/tag/3789120821_linux since it has the manpage and doesn't include the binary blobs.

**Comment by maltfield** [comment] 2023-06-17 23:27
This has been documented in the Release Workflow section of our documentation

 * https://docs.buskill.in/buskill-app/en/v0.7.0/software_dev/release.html#build-sign

Example

 * https://github.com/BusKill/buskill-app/releases/tag/v0.7.0

**Closed by maltfield** 2023-06-17 23:27 UTC
