### ISSUE TITLE
Delay in locking on MacBook

### ISSUE THREAD

**Issue by stevenj2019** [BusKill/buskill-app#12] opened 2020-09-25 13:47 UTC
**Describe the bug**
when removing USB Device on BusKill - Mac the laptop can be woken up without a password. when executing command it does work. 
The Delay creates a possible risk 

**To Reproduce**
1. Go to 'BusKill'
2. Click on 'Arm'
3. Remove USB Device
4. Screen Dims but mouse wiggle wakes the device 

Mac Should lock and require a password/authentication
**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.5
 - N/A 
 - Version 0.2.0

**Comment by maltfield** [comment] 2020-09-26 05:51
Thanks for finding & reporting this @stevenj2019 !

Unfortunately, MacOS is the one OS that I don't have physical access to, so I'm mostly writing that `triggerMac()` function blind and testing it by proxy through @jneplokh

Per our conversation, please replace the `try` block that causes this issue while also testing older versions of MacOS to make sure that it works on older versions as well. Please update this ticket with your progress.

Thank you!

**Comment by stevenj2019** [comment] 2020-10-19 18:25
Testing Command Functionality for kernel versions 17.x - 19.x 

19.x corrected in forked project, 
Testing and Implementation for 17.x and 18.x to be completed

**Comment by stevenj2019** [comment] 2020-10-19 21:15
Testing for High-Sierra(17.x) conducted via VM ran on Mac Host. 

Fix added into forked repo 

(VBOX FILE ATTACHED)
[High-Sierra.vbox.txt](https://github.com/BusKill/buskill-app/files/5404787/High-Sierra.vbox.txt)
Remove the .txt from the file to use with virtualbox for mac or linux

**Comment by stevenj2019** [comment] 2020-11-07 12:48
Testing for Mojave (18.x) conducted via VM ran on Mac Host. 

Fix added into forked repo 

(VBOX FILE ATTACHED
[Mojave.vbox.txt](https://github.com/BusKill/buskill-app/files/5504745/Mojave.vbox.txt)
)

Remove the .txt from the file to use with virtualbox for mac or linux

**Comment by stevenj2019** [comment] 2020-11-07 12:53
PR requested to main repo from fork in [Pull Request](https://github.com/BusKill/buskill-app/pull/15)

**Comment by maltfield** [comment] 2021-09-26 17:13
Today I merged @stevenj2019's build from PR #15 to fix this, but I can't test it as I don't have a MacBook

**Comment by maltfield** [comment] 2021-11-14 21:59
Melanie said she cannot reproduce the issue on the latest build, so I'm going to close this.

**Closed by maltfield** 2021-11-14 21:59 UTC
Labels: bug
